import { Router } from 'express';
import authRoutes from './auth.routes.js';
import usersRoutes from './users.routes.js';
import machinesRoutes from './machines.routes.js';
import productsRoutes from './products.routes.js';
import cartRoutes from './cart.routes.js';
import feedbackRoutes from './feedback.routes.js';
import notificationsRoutes from './notifications.routes.js';
import paymentsRoutes from './payments.routes.js';
import campaignsRoutes from './campaigns.routes.js';
import contentRoutes from './content.routes.js';
import machinesQrRoutes from './machines.qr.routes.js';
import healthRoutes from './health.routes.js';
import docsRoutes from './docs.routes.js';
import legacyRoutes from './legacy.routes.js';
import adminApiRoutes from './admin.api.routes.js';
export const router = Router();
router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/machines', machinesRoutes);
router.use('/products', productsRoutes);
router.use('/cart', cartRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/payments', paymentsRoutes);
router.use('/campaigns', campaignsRoutes);
router.use('/content', contentRoutes);
router.use('/machines', machinesQrRoutes);
router.use('/health', healthRoutes);
router.use('/docs', docsRoutes);
router.use('/admin', adminApiRoutes);
router.get('/', (_req, res) => res.render('welcome', { title: 'Vend-IT' }));
router.use('/', legacyRoutes);
export default router;
