import { Router } from 'express';
import { handleCardPayment, handleChargeWallet, handleDeleteCard, handleDispenseUpdate, handleGPayPayment, handleGPayToken, handleIosPayment, handleListCards, handleLoyaltyHistory, handleOrderHistory, handlePaymentHistory, handleWalletHistory, handleWalletPayment, handleCreateCard } from '../modules/payments/payments.controller.js';
import { requireAuth } from '../middleware/auth.js';
const router = Router();
router.use(requireAuth);
router.post('/cards', handleCreateCard);
router.get('/cards', handleListCards);
router.delete('/cards/:cardId', handleDeleteCard);
router.post('/wallet/charge', handleChargeWallet);
router.post('/wallet/pay', handleWalletPayment);
router.post('/card/pay', handleCardPayment);
router.post('/ios/pay', handleIosPayment);
router.post('/gpay/token', handleGPayToken);
router.post('/gpay/pay', handleGPayPayment);
router.post('/dispense', handleDispenseUpdate);
router.get('/history', handlePaymentHistory);
router.get('/wallet/history', handleWalletHistory);
router.get('/orders/history', handleOrderHistory);
router.get('/loyalty/history', handleLoyaltyHistory);
export default router;
